DELETE FROM PROJECT_LANGUAGE;
DELETE FROM PROJECT_USER;
DELETE FROM RELEASE_DEFINITION;
DELETE FROM RELEASE;
DELETE FROM TRANSLATION;
DELETE FROM LANGUAGE;
DELETE FROM DEFINITION;
DELETE FROM PROJECT;
DELETE FROM OAUTH_ACCESS_TOKEN;
DELETE FROM JHI_USER_AUTHORITY WHERE USER_ID > 4;
DELETE FROM JHI_USER WHERE ID > 4;

INSERT INTO JHI_USER (ID, LOGIN, PASSWORD_HASH, FIRST_NAME, LAST_NAME, EMAIL, ACTIVATED, LANG_KEY, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY) VALUES (5,'customer','$2a$10$VEjxo0jq2YG9Rbk2HmX9S.k1uZBGYUHdUcid3g/vfiEl7lwWgOH/K','Customer','Customer','customer@localhost',true,'de','system', NOW(), 'system');
INSERT INTO JHI_USER_AUTHORITY VALUES (5, 'ROLE_CUSTOMER');
INSERT INTO JHI_USER (ID, LOGIN, PASSWORD_HASH, FIRST_NAME, LAST_NAME, EMAIL, ACTIVATED, LANG_KEY, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY) VALUES (6,'translator','$2a$10$VEjxo0jq2YG9Rbk2HmX9S.k1uZBGYUHdUcid3g/vfiEl7lwWgOH/K','TranslatorVorname','TranslatorNachname','mailing2philipp@gmail.com',true,'de','system', NOW(), 'system');
INSERT INTO JHI_USER_AUTHORITY VALUES (6, 'ROLE_TRANSLATOR');
INSERT INTO JHI_USER (ID, LOGIN, PASSWORD_HASH, FIRST_NAME, LAST_NAME, EMAIL, ACTIVATED, LANG_KEY, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY) VALUES (7,'developer','$2a$10$VEjxo0jq2YG9Rbk2HmX9S.k1uZBGYUHdUcid3g/vfiEl7lwWgOH/K','Developer','Developer','developer@localhost',true,'de','system', NOW(), 'system');
INSERT INTO JHI_USER_AUTHORITY VALUES (7, 'ROLE_DEVELOPER');
INSERT INTO JHI_USER (ID, LOGIN, PASSWORD_HASH, FIRST_NAME, LAST_NAME, EMAIL, ACTIVATED, LANG_KEY, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY) VALUES (8,'releasemanager','$2a$10$VEjxo0jq2YG9Rbk2HmX9S.k1uZBGYUHdUcid3g/vfiEl7lwWgOH/K','ReleaseManager','ReleaseManager','releasemanager@localhost',true,'de','system', NOW(), 'system');
INSERT INTO JHI_USER_AUTHORITY VALUES (8, 'ROLE_RELEASE_MANAGER');

INSERT INTO PROJECT VALUES (1, 'Project 1', 'Description of project 1');
INSERT INTO PROJECT VALUES (2, 'Project 2', 'Description of project 2');

INSERT INTO LANGUAGE VALUES (1, 'German', 'DE', 5);
INSERT INTO LANGUAGE VALUES (2, 'Spanish', 'ES', 5);

INSERT INTO PROJECT_LANGUAGE VALUES (1, 1);
INSERT INTO PROJECT_LANGUAGE VALUES (2, 1);

INSERT INTO PROJECT_USER VALUES (5, 1);
INSERT INTO PROJECT_USER VALUES (6, 1);
INSERT INTO PROJECT_USER VALUES (7, 1);
INSERT INTO PROJECT_USER VALUES (8, 1);

INSERT INTO DEFINITION VALUES (1, 'house', 'House', 1, NOW(), NOW(), 1);
INSERT INTO DEFINITION VALUES (2, 'car', 'Car', 1, NOW(), NOW(), 1);
INSERT INTO DEFINITION VALUES (3, 'error', 'Error', 1, NOW(), NOW(), 1);
INSERT INTO DEFINITION VALUES (4, 'someErrorOccured', 'Some error occured', 1, NOW(), NOW(), 1);
INSERT INTO DEFINITION VALUES (5, 'pleaseEnterAValidEmailAddress', 'Please enter a valid email address', 1, NOW(), NOW(), 2);
INSERT INTO DEFINITION VALUES (6, 'house', 'House', 2, NOW(), NOW(), 1);
INSERT INTO DEFINITION VALUES (7, 'car', 'Car', 2, NOW(), NOW(), 1);
INSERT INTO DEFINITION VALUES (8, 'error', 'Error', 2, NOW(), NOW(), 1);
INSERT INTO DEFINITION VALUES (9, 'error', 'Error', 3, NOW(), NOW(), 1);

INSERT INTO TRANSLATION VALUES (1, 'Haus', false, NOW(), 1, 1);
INSERT INTO TRANSLATION VALUES (2, 'Auto', false, NOW(), 2, 1);
INSERT INTO TRANSLATION VALUES (3, 'Fehler', false, NOW(), 3, 1);
INSERT INTO TRANSLATION VALUES (4, 'Ein Fehler ist aufgetreten', false, NOW(), 4, 1);
INSERT INTO TRANSLATION VALUES (5, 'Bitte geben Sie eine gültige E-Mail Adresse ein', false, NOW(), 5, 1);
INSERT INTO TRANSLATION VALUES (6, 'HausV2', false, NOW(), 6, 1);
INSERT INTO TRANSLATION VALUES (7, 'AutoV2', false, NOW(), 7, 1);
INSERT INTO TRANSLATION VALUES (8, 'FehlerV2', false, NOW(), 8, 1);
INSERT INTO TRANSLATION VALUES (9, 'FehlerV3', false, NOW(), 9, 1);
INSERT INTO TRANSLATION VALUES (10, 'Casa', false, NOW(), 1, 2);
INSERT INTO TRANSLATION VALUES (11, 'Casa', false, NOW(), 6, 2);
INSERT INTO TRANSLATION VALUES (12, 'Se produjo un error', false, NOW(), 4, 2);

INSERT INTO RELEASE VALUES (1, 'Release 1', '2017-01-01', 1, 'FINSIHED', 0);
INSERT INTO RELEASE VALUES (2, 'Release 2', '2017-02-02', 1, 'DEFINITIONS_ASSIGNED', 0);

INSERT INTO RELEASE_DEFINITION VALUES (1, 1);
INSERT INTO RELEASE_DEFINITION VALUES (2, 1);
INSERT INTO RELEASE_DEFINITION VALUES (3, 1);
INSERT INTO RELEASE_DEFINITION VALUES (4, 1);
INSERT INTO RELEASE_DEFINITION VALUES (5, 1);
INSERT INTO RELEASE_DEFINITION VALUES (1, 2);
INSERT INTO RELEASE_DEFINITION VALUES (2, 2);
INSERT INTO RELEASE_DEFINITION VALUES (8, 2);
INSERT INTO RELEASE_DEFINITION VALUES (9, 2);